# Generated by Django 3.1.4 on 2021-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210505_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
